In [2]:
import pandas as pd

df = pd.read_csv("final_ecommerce_data.csv")

df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_installments,payment_value,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,year,month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,18.12,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2017,10
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,2.00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2017,10
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,18.59,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2017,10
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,1.0,141.46,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,2018,7
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,3.0,179.12,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,2018,8

In [3]:
import sqlite3

conn = sqlite3.connect("ecommerce.db")

df.to_sql("ecommerce_data", conn, if_exists="replace", index=False)

print("Table created successfully")

Table created successfully

In [6]:
#Total Revenue
query = """
SELECT ROUND(SUM(payment_value), 2) AS total_revenue
FROM ecommerce_data;
"""

pd.read_sql_query(query, conn)

   total_revenue
0    20470726.66

In [7]:
#Total Orders
query = """
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce_data;
"""

pd.read_sql_query(query, conn)

   total_orders
0         99441

In [8]:
#Total Customers
query = """
SELECT COUNT(DISTINCT customer_unique_id) AS total_customers
FROM ecommerce_data;
"""

pd.read_sql_query(query, conn)

   total_customers
0            96096

In [9]:
#Revenue by State
query = """
SELECT customer_state,
       ROUND(SUM(payment_value), 2) AS total_revenue
FROM ecommerce_data
GROUP BY customer_state
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  customer_state  total_revenue
0             SP     7673188.55
1             RJ     2783724.26
2             MG     2341861.47
3             RS     1152019.17
4             PR     1074614.19
5             BA      802416.72
6             SC      799135.92
7             GO      516182.51
8             DF      434512.55
9             ES      406946.26

In [10]:
#Monthly Revenue Trend
query = """
SELECT year,
       month,
       ROUND(SUM(payment_value), 2) AS monthly_revenue
FROM ecommerce_data
GROUP BY year, month
ORDER BY year, month;
"""

pd.read_sql_query(query, conn)

    year  month  monthly_revenue
0   2016      9           388.47
1   2016     10         76120.17
2   2016     12            19.62
3   2017      1        189015.66
4   2017      2        349701.93
5   2017      3        544738.23
6   2017      4        510891.55
7   2017      5        731017.09
8   2017      6        608891.38
9   2017      7        744599.53
10  2017      8        876129.37
11  2017      9       1023095.49
12  2017     10       1031505.53
13  2017     11       1599444.18
14  2017     12       1057582.34
15  2018      1       1415348.54
16  2018      2       1311260.71
17  2018      3       1480045.50
18  2018      4       1497843.94
19  2018      5       1511113.00
20  2018      6       1298685.81
21  2018      7       1359421.48
22  2018      8       1248837.93
23  2018      9          4439.54
24  2018     10           589.67

In [12]:
#Top 10 Customers by Revenue
query = """
SELECT customer_unique_id,
       ROUND(SUM(payment_value), 2) AS total_revenue
FROM ecommerce_data
GROUP BY customer_unique_id
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                 customer_unique_id  total_revenue
0  0a0a92112bd4c708ca5fde585afaa872      109312.64
1  698e1cf81d01a3d389d96145f7fa6df8       45256.00
2  c402f431464c72e27330a67f7b94d4fb       44048.00
3  4007669dec559734d6f53e029e360987       36489.24
4  ef8d54b3797ea4db1d63f0ced6a906e9       30186.00
5  763c8b1c9c68a0229c42c9fc6f662b93       29099.52
6  c8460e4251689ba205045f3ea17884a1       27935.46
7  eae0a83d752b1dd32697e0e7b4221656       25051.89
8  3d47f4368ccc8e1bb4c4a12dbda7111b       22346.60
9  adfa1cab2b2c8706db21bb13c0a1beb1       19457.04